default_language_version:
  node: 16.15.0
  ruby: 2.7.2
  python: python3.12

repos:
  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: ^application/ui/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1"
    hooks:
      - id: mypy
        alias: mypy_lib
        name: mypy (lib)
        files: '^lib/(src/otx)/.*\.py'
        additional_dependencies:
          [
            types-PyYAML,
            attrs==21.2.*,
            types-aiofiles,
            types-requests,
            types-Deprecated,
            types-docutils,
            types_futures,
            types-setuptools,
            types-python-dateutil,
            tokenize-rt==3.2.0,
          ]
        args: [--disallow-untyped-calls, --config-file, lib/pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.12.0"
    hooks:
      - id: mypy
        alias: mypy_backend
        name: mypy (backend)
        files: '^backend/.*\.py'
        additional_dependencies: [types-PyYAML, types-aiofiles, types-requests]
        args: [--disallow-untyped-calls, --config-file, backend/pyproject.toml]

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck # TODO remove this when all shell scripts have been removed from otx

  # markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yaml]

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
