input:
  source_type: video_file  # [webcam, ip_camera, video_file, images_folder]
  video_path: data/media/video.mp4
outputs:
  - destination_type: folder  # [folder, mqtt, dds, ros]
    folder_path: data/output
    output_formats:
      - image_original
      - image_with_predictions
      - predictions
    rate_limit: 0.2  # output every 5 seconds
