x-proxies: &proxies
  args:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - no_proxy=${no_proxy}

services:
  server:
    image: geti-tune-backend:${TAG:-latest}
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      <<: *proxies
    depends_on:
      - reverse-proxy
    working_dir: /app
    volumes:
      - ./data/:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-tune-server.rule=Host(`${GETI_TUNE_DOMAIN:-geti-tune.localhost}`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.geti-tune-server.entrypoints=web"
      - "traefik.http.services.geti-tune-server.loadbalancer.server.port=7860"

  client:
    image: geti-tune-ui:${TAG:-latest}
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./ui
      <<: *proxies
    depends_on:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-tune-client.rule=Host(`${GETI_TUNE_DOMAIN:-geti-tune.localhost}`)"
      - "traefik.http.routers.geti-tune-client.entrypoints=web"
      - "traefik.http.services.geti-tune-client.loadbalancer.server.port=80"

  reverse-proxy:
    image: traefik:v3.4.1@sha256:cd40ab7bc1f047731d5b22595203812343efcb6538014c4e93221cfc3a77217a
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-tune-proxy.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.geti-tune-proxy.entrypoints=web"
      - "traefik.http.services.geti-tune-proxy.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
