x-proxies: &proxies
  args:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - NO_PROXY=${NO_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - no_proxy=${no_proxy}

services:
  server:
    image: geti-edge-backend:dev
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      <<: *proxies
    develop:
      watch:
        # sync static content
        - path: ./app/
          action: sync
          target: /app/app/
    depends_on:
      - reverse-proxy
    command: uv run fastapi dev --host 0.0.0.0 --port 7860
    volumes:
      - ./data/:/app/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-edge-server.rule=Host(`${GETI_EDGE_DOMAIN:-geti-edge.localhost}`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.geti-edge-server.entrypoints=web"
      - "traefik.http.services.geti-edge-server.loadbalancer.server.port=7860"

  client:
    image: geti-edge-ui:dev
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./ui
      target: dev
      <<: *proxies
    depends_on:
      - reverse-proxy
    develop:
      watch:
        # sync static content
        - path: ./ui/
          action: sync
          target: /home/app/web_ui/
          ignore:
            - node_modules/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-edge-client.rule=Host(`${GETI_EDGE_DOMAIN:-geti-edge.localhost}`)"
      - "traefik.http.routers.geti-edge-client.entrypoints=web"
      - "traefik.http.services.geti-edge-client.loadbalancer.server.port=3000"


  reverse-proxy:
    image: traefik:v3.4.1@sha256:cd40ab7bc1f047731d5b22595203812343efcb6538014c4e93221cfc3a77217a
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geti-edge-proxy.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.geti-edge-proxy.entrypoints=web"
      - "traefik.http.services.geti-edge-proxy.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
