id: Custom_Counting_Instance_Segmentation_MaskRCNN_SwinT_FP16
name: MaskRCNN-SwinT-FP16

pretrained_weights:
  url: https://download.openmmlab.com/mmdetection/v2.0/swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco_20210908_165006-90a4008c.pth
  sha_sum: 90a4008ce84011fc0d75a08db1b65b01ee1f145e9a1dffe8acc15ea8894b348d

description: "This model combines the Mask R-CNN framework with a Swin-Tiny transformer backbone, leveraging hierarchical attention and shifted windows for better spatial understanding. It delivers enhanced instance segmentation performance, especially on complex scenes, while maintaining a lightweight transformer design."
stats:
  gigaflops: 264.0
  trainable_parameters: 47.4
  performance_ratings: # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1

hyperparameters:
  training:
    learning_rate: 0.0001
    input_size_width: 1344
    input_size_height: 1344
