id: Custom_Counting_Instance_Segmentation_MaskRCNN_ResNet50
name: MaskRCNN-ResNet50

pretrained_weights:
  url: https://download.openmmlab.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_fpn_mstrain-poly_3x_coco/mask_rcnn_r50_fpn_mstrain-poly_3x_coco_20210524_201154-21b550bb.pth
  sha_sum: 21b550bb3aa94fbaf85592931466a27b90520422c8b1f2ac08ddf4cf1e4fd650

description: "Mask R-CNN with a ResNet-50 backbone is a widely used instance segmentation model that balances accuracy and speed. The ResNet-50 backbone provides strong feature extraction, while the Mask R-CNN head enables precise object detection and mask prediction for each instance. Note: this version is deprecated, please use v2 if possible."
stats:
  gigaflops: 200.0
  trainable_parameters: 47.8
  performance_ratings: # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 2
    inference_speed: 2
support_status: deprecated

hyperparameters:
  training:
    learning_rate: 0.007
