id: Object_Detection_ResNeXt101_ATSS
name: ATSS-ResNeXt101

pretrained_weights:
  url: https://storage.openvinotoolkit.org/repositories/openvino_training_extensions/models/object_detection/v2/resnext101_atss_070623.pth
  sha_sum: 1515fb8de866c905c11172e160250044b8ecdb306334a4ba271f28f2c6ec3ccf

description: "ATSS (Adaptive Training Sample Selection) is an anchor-based object detection algorithm that introduces an adaptive strategy for selecting positive and negative samples during training. Instead of using fixed IoU thresholds, ATSS dynamically determines positive samples based on the statistical characteristics of object candidates for each ground truth. This improves training stability and enhances detection performance, especially for objects of varying sizes and aspect ratios."
stats:
  gigaflops: 20.6
  trainable_parameters: 3.9
  performance_ratings: # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 1
support_status: deprecated

hyperparameters:
  training:
    learning_rate: 0.004
