id: Object_Detection_Deim_DFine_M
name: Deim-DFine-M

pretrained_weights:
  url: https://github.com/eugene123tw/DEIM/releases/download/poc/deim_dfine_hgnetv2_m_coco_90e.pth
  sha_sum: 2b6cd0582a4aa711f583982057b7fb0f3daebdd98e4dc168824714014c3219bc

description: "DEIM is an advanced training framework designed to enhance the matching mechanism in DETRs, enabling faster convergence and improved accuracy."
stats:
  gigaflops: 57
  trainable_parameters: 19
  performance_ratings: # scores range from 1 (below average) to 3 (excellent)
    accuracy: 2
    training_time: 2
    inference_speed: 2

hyperparameters:
  training:
    learning_rate: 0.0004
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      iou_random_crop: null
      random_affine: null
      random_horizontal_flip: null
      random_vertical_flip: null
      gaussian_blur: null
      color_jitter: null
      gaussian_noise: null
