id: Object_Detection_RTDetr_50
name: RTDetr-R50

pretrained_weights:
  url: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_2x_coco_objects365_from_paddle.pth
  sha_sum: 7788173453f771d45d0b49ffa23dbeb60796ccb8425afa52befb0b8fe033608c

description: "RT-DETR is a real-time object detection algorithm based on the transformer architecture. It combines a convolutional backbone with an efficient encoder-decoder transformer to directly predict object classes and bounding boxes without the need for anchor boxes or NMS."
stats:
  gigaflops: 136
  trainable_parameters: 42
  performance_ratings: # scores range from 1 (below average) to 3 (excellent)
    accuracy: 3
    training_time: 1
    inference_speed: 2

hyperparameters:
  training:
    learning_rate: 0.0001
    input_size_width: 640
    input_size_height: 640
