default_language_version:
  python: python3.13 # Should match the Python version used by the app (set in backend/pyproject.toml)

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.9.7"
    hooks:
      - id: uv-lock
        name: uv lock

  - repo: local
    hooks:
      - id: pyrefly-check
        name: pyrefly-check
        entry: uv run pyrefly check
        pass_filenames: false
        language: system

  - repo: https://github.com/seddonym/import-linter
    rev: "v2.3"
    hooks:
      - id: import-linter
        name: import linter
        args: [--no-cache]
