name: Daily Integration Test

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    # every UTC/GMT 8PM from Mon to Fri
    - cron: "0 20 * * 1-5"

# Declare default permissions as read only.
permissions: read-all

jobs:
  Daily-Integration-Tests:
    runs-on: [daily]
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: "multi_class_cls"
          - task: "multi_label_cls"
          - task: "h_label_cls"
          - task: "anomaly"
          - task: "keypoint_detection"
          - task: "detection"
          - task: "instance_segmentation"
          - task: "semantic_segmentation"
    name: Daily-Integration-Test-${{ matrix.task }}-py312
    concurrency:
      group: Daily-${{ github.workflow }}-${{ github.ref }}-${{ matrix.task }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"
      - name: Install tox
        working-directory: lib
        run: |
          pip install '.[dev]'
      - name: Run Daily Integration Test
        working-directory: lib
        run: tox -vv -e daily-integration-test-${{ matrix.task }} -- --run-category-only=False
