name: Daily Integration Test

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    # every UTC/GMT 8PM from Mon to Fri
    - cron: "0 20 * * 1-5"

# Declare default permissions as read only.
permissions: read-all

jobs:
  Daily-Integration-Tests:
    runs-on: otx-ci-3090-03-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: "multi_cls_classification"
          - task: "multi_label_classification"
          - task: "hlabel_classification"
          - task: "visual_prompting"
          - task: "anomaly"
          - task: "keypoint_detection"
          - task: "detection"
          - task: "instance_segmentation"
          - task: "semantic_segmentation"
    name: Daily-Integration-Test-${{ matrix.task }}-py310
    concurrency:
      group: Daily-${{ github.workflow }}-${{ github.ref }}-${{ matrix.task }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python -m pip install --require-hashes --no-deps -r .ci/requirements.txt
          pip-compile --generate-hashes --output-file=/tmp/requirements.txt --extra=ci_tox pyproject.toml
          python -m pip install --require-hashes --no-deps -r /tmp/requirements.txt
          rm /tmp/requirements.txt
      - name: Run Integration Test
        run: tox -vv -e daily-integration-test-${{ matrix.task }}
