#####
# This workflow is triggered by pull_request_target event.
# Never checkout the PR and run ANY local code on it.
#####

name: "Pull Request Labeler"
on:
  # The labeler doesn't checkout/execute any contributed code, so it should be safe.
  - pull_request_target # zizmor: ignore[dangerous-triggers]

permissions: {} # No permissions by default on workflow level

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.1.0
