name: Geti Tune Library checks

on:
  push:
    branches:
      - develop
      - release/**
    tags:
      - "v*"
  pull_request:
  merge_group:
    branches:
      - develop
      - release/**
  workflow_dispatch: # run on request (no need for PR)

permissions: {} # No permissions by default

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  # Determines if workflow should execute based on event type and changed paths
  # If push or workflow_dispatch -> always run
  # If PR or merge_group -> run only if files in specified paths changed
  check-paths:
    name: Check if workflow should run
    runs-on: ubuntu-latest
    outputs:
      run_workflow: ${{ steps.run_workflow.outputs.run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Get all paths that should trigger the workflow
        id: changed-files-yaml
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files_yaml: |
            test:
              - library/**
              - .github/**

      - name: Set run flag
        id: run_workflow
        run: |
          if [ "${{ github.event_name }}" = "push" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.changed-files-yaml.outputs.test_any_changed }}" = "true" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

  code-quality-checks:
    runs-on: ubuntu-24.04
    needs: check-paths
    if: needs.check-paths.outputs.run_workflow == 'true'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          version: "0.9.7"
          enable-cache: false

      - name: Installing dependencies
        working-directory: library
        run: |
          uv lock --check
          uv sync --frozen

      - name: Check formatting with ruff
        working-directory: library
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .

      # TODO: remove 'continue-on-error' after addressing all mypy issues
      # https://github.com/open-edge-platform/training_extensions/issues/5006
      - name: Check source code with mypy
        continue-on-error: true
        working-directory: library
        run: |
          uv run mypy src/otx

  unit-tests:
    runs-on: [self-hosted, linux, x64, dev, dmount]
    permissions:
      contents: read
      # The id-token permission is required by Codecov to use OIDC
      id-token: write
    needs:
      - code-quality-checks
      - check-paths
    if: needs.check-paths.outputs.run_workflow == 'true'
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]
    name: unit-tests-with-Python${{ matrix.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          version: "0.9.7"
          enable-cache: false

      - name: Installing dependencies
        working-directory: library
        run: |
          uv lock --check
          uv sync --frozen

      - name: Unit testing
        working-directory: library
        run: uv run pytest tests/unit --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          directory: library
          flags: coverage_unit-tests_Python-${{ matrix.python-version }}
          use_oidc: true

  integration-tests:
    runs-on: [self-hosted, linux, x64, dev, dmount]
    permissions:
      contents: read
    needs:
      - unit-tests
      - check-paths
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.13"]
        include:
          - task: "multi_class_cls"
          - task: "multi_label_cls"
          - task: "h_label_cls"
          - task: "keypoint_detection"
          - task: "detection"
          - task: "instance_segmentation"
          - task: "semantic_segmentation"
    name: integration-tests-${{ matrix.task }}-py${{ matrix.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          version: "0.9.7"
          enable-cache: false

      - name: Installing dependencies
        working-directory: library
        run: |
          uv lock --check
          uv sync --frozen --extra cuda

      - name: Integration testing
        working-directory: library
        env:
          CUBLAS_WORKSPACE_CONFIG: ":4096:8"
        run: |
          uv run --frozen --extra cuda pytest tests/integration \
            -ra \
            --showlocals \
            --csv=${{ matrix.task }}_Python-${{ matrix.python-version }}.csv \
            --task ${{ matrix.task }} \
            --open-subprocess \
            --run-category-only

  required-check:
    name: Required Check lib-lint-and-test
    needs:
      - check-paths
      - code-quality-checks
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    env:
      CHECKS: ${{ join(needs.*.result, ' ') }}
    if: always() && !cancelled()
    steps:
      - name: Check jobs results
        run: |
          for check in ${CHECKS}; do
            echo "::notice::check=${check}"
            if [[ "$check" != "success" && "$check" != "skipped" ]]; then
              echo "::error ::Required status checks failed. They must succeed before this pull request can be merged."
              exit 1
            fi
          done
