name: Geti Tune server checks
on:
  push:
    branches: ["develop"]
  pull_request:

permissions: {} # No permissions by default on workflow level

jobs:
  python-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout code
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@a02a550bdd3185dba2ebb6aa98d77047ce54ad21 # v6.2.1
        with:
          version: "0.8.8"

      - name: Install OpenCV dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 \
            libglib2.0-0

      - name: Prepare venv and install Python dependencies
        working-directory: backend
        run: |
          uv lock --check
          uv sync --frozen --all-extras

      - name: Check formatting with ruff
        working-directory: backend
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check .

      - name: Check source code with mypy
        working-directory: backend
        run: |
          uv run mypy . --config-file=pyproject.toml

      - name: Run unit tests
        working-directory: backend
        run: |
          uv run pytest tests/unit

      - name: Run integration tests
        working-directory: backend
        run: |
          uv run pytest tests/integration
